version: "3.8"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: meuvestibulinho
      POSTGRES_DB: meuvestibulinho
    volumes:
      - ./dev-env/postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: ["start-dev", "--import-realm"]
    environment:
      - DB_VENDOR=postgres
      - KC_DB=postgres
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=password
      - KC_DB_URL=jdbc:postgresql://postgres-keycloak:5432/postgres
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    volumes:
      - ./dev-env/keycloak/data/import:/opt/keycloak/data/import
    ports:
      - "8080:8080"
    depends_on:
      - postgres-keycloak
  postgres-keycloak:
    image: postgres:latest
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
    volumes:
      - ./dev-env/keycloak/db:/var/lib/postgresql/data/
    
